### ISSUE TITLE
Storage failed to publish to vcpkg

### ISSUE THREAD

**Issue by Jinming-Hu** [Azure/azure-sdk-for-cpp#3077] opened 2021-11-08 05:40 UTC
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1183243&view=logs&j=3852a3f0-0201-5e58-cdca-c5862b5986a9&t=180ac29e-137b-5a29-bcba-efb3278292e2

**Comment by Jinming-Hu** [comment] 2021-11-08 05:40
Hi @danieljurek , can you please take a look?

**Comment by Jinming-Hu** [comment] 2021-11-08 06:25
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1183298&view=logs&j=5cf85578-dfa7-590f-0a30-32d2675fdd83&t=94cc6b13-ecb8-5a94-3aca-c87e8d1e407c

**Comment by danieljurek** [comment] 2021-11-08 18:57
Hey @Jinming-Hu, in both cases I see that we succeeded in publishing to vcpkg -- https://github.com/microsoft/vcpkg/pull/21247 

The step which comments on the bug is failing right now because of a regression in `eng/common` ... We're working on fixing that.

**Comment by ahsonkhan** [comment] 2021-11-08 20:00
The release was successful, so removing blocking-release :)

**Comment by ahsonkhan** [comment] 2021-11-08 20:01
Also, duplicate of https://github.com/Azure/azure-sdk-for-cpp/issues/3061
Closing.

**Closed by ahsonkhan** 2021-11-08 20:01 UTC
Labels: EngSys, Central-EngSys
