### ISSUE TITLE
Support managed identities in cpp sdk

### ISSUE THREAD

**Issue by spacedragon** [Azure/azure-sdk-for-cpp#741] opened 2020-10-12 03:34 UTC
**Is your feature request related to a problem? Please describe.**
Support managed identities
https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/overview

**Describe the solution you'd like**
Something like https://github.com/Azure/azure-sdk-for-net/blob/89966952801549fb89b0626072b325864a30281e/sdk/identity/Azure.Identity/src/ManagedIdentityCredential.cs
in C# SDK 

**Describe alternatives you've considered**

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Description Added
- [ ] Expected solution specified

**Comment by Jinming-Hu** [comment] 2020-10-12 03:47
unlike the method we already have to get an access token (via tenant ID, client ID, client secret), the method this customer is requesting is getting and refreshing token by sending a request to a customized URL like `http://169.254.169.254/metadata/identity/oauth2/token` without any other information.

**Comment by RickWinter** [comment] 2020-10-12 17:01
Thank you for the feedback.  At this time we are working on the Core Azure::Identity framework.  Once we have that in place we will consider adding this and other credential types

**Comment by antkmsft** [comment] 2020-10-12 19:29
Closing as a duplicate of https://github.com/Azure/azure-sdk-for-cpp/issues/81.

**Closed by antkmsft** 2020-10-12 19:29 UTC
Labels: Azure.Identity, Client, customer-reported, feature-request
