### ISSUE TITLE
Storage test `BlobSasTest.AccountSasService` keeps failing in CI after adding table service

### ISSUE THREAD

**Issue by gearama** [Azure/azure-sdk-for-cpp#5229] opened 2023-12-15 18:19 UTC
**Describe the bug**
TEST_F(BlobSasTest, AccountSasService_LIVEONLY_) // keeps failing in CI 
***Exception or Stack Trace***
Add the exception log and stack trace if available

**To Reproduce**

***Code Snippet***
Add the code snippet that causes the issue.

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - IDE : [e.g. IntelliJ]
 - Version of the Library used

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by ahsonkhan** [comment] 2023-12-18 19:46
@gearama what's the error text? Can you please paste a link to the pipeline build that failed (especially if it is intermittent) and any other relevant details?

**Comment by Jinming-Hu** [comment] 2023-12-20 05:45
This is likely to be caused by an extra service `table` in signed service (`ss`) in the SAS token.

Before we added table support, the signed service(s) in SAS token include blob, file, queue, like `ss=bfq`. After we added table, it became `ss=bfqt`. The difference of `ss` query parameter will cause mismatch between playback requests and recording. We'll need to redo the recording to fix this issue.

**Comment by antkmsft** [comment] 2024-01-18 16:06
This issue was logged back when Tables were still in PR, and at a time it was going to add some functionality to Storage-Common.
That is no longer the case. Tables is merged to main, and it only depends on Core. Storage tests are not failing.
@gearama, can this issue be closed?

**Comment by RickWinter** [comment] 2024-03-12 00:29
@gearama Can this issue be closed?

**Closed** 2024-03-12 18:56 UTC
Labels: Client, Tables, test-reliability
