### ISSUE TITLE
Audit all uses of static_cast and reinterpret_cast and add comments where we know they are safe and guaranteed to work

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#2416] opened 2021-06-07 20:11 UTC
For code maintainability and reduce the risk of bugs introduced due to unintentional assumptions, audit arguments and function code flow using inference, and add comments to places where `static_cast` is used that indicate they are guaranteed to succeed.

An example of a comment helping the reader understand:
https://github.com/Azure/azure-sdk-for-cpp/blob/17b91ffe598cf17bb4755480b70a9bb6fb3a02f3/sdk/core/azure-core/inc/azure/core/uuid.hpp#L94-L95

Here's an example where such an audit and comment might be helpful, do the same for other places as well, unless it is immediately obvious why the cast is safe:
https://github.com/Azure/azure-sdk-for-cpp/blob/17b91ffe598cf17bb4755480b70a9bb6fb3a02f3/sdk/core/azure-core/src/datetime.cpp#L261

Do the same for `reinterpret_cast`, for example:
https://github.com/Azure/azure-sdk-for-cpp/blob/17b91ffe598cf17bb4755480b70a9bb6fb3a02f3/sdk/core/azure-core/src/cryptography/md5.cpp#L49

Here's an example, where the code is self-documenting and it is clear that this cast is safe:
https://github.com/Azure/azure-sdk-for-cpp/blob/17b91ffe598cf17bb4755480b70a9bb6fb3a02f3/sdk/core/azure-core/inc/azure/core/context.hpp#L203

**Comment by vhvb1989** [comment] 2021-07-28 01:22
@ahsonkhan , static_cast is going to fail during compile time. I don't think we need to check those

**Comment by antkmsft** [comment] 2021-08-12 19:34
My opinion about this: https://github.com/Azure/azure-sdk-for-cpp/pull/2710#pullrequestreview-727145018

But I also think priority-wise that we have to see at least one bug caused by this before we invest more time into it. So far, we reviewed them proactively without suspecting or seeing any bugs caused by this, and it is good enough to close it after just a review. The future instances of casts will be reviewed during code reviews.

**Comment by vhvb1989** [comment] 2021-08-17 17:34
After talking and looking the best approach to fix this issue. The team have decided to lower priority on this and consider the initial and simple code inspection as enough.  Hence, closing this issue.

No further action on this subject is expected

**Closed by vhvb1989** 2021-08-17 17:34 UTC
Labels: bug, Azure.Core, Client, Epic
