### ISSUE TITLE
Let Blob::GetProperties() Blob::Download() methods be tolerant to the missing "x-ms-creation-time" header OR introduce a descriptive exception

### ISSUE THREAD

**Issue by kshcherbatov** [Azure/azure-sdk-for-cpp#2717] opened 2021-08-08 09:18 UTC
**Query/Question**
AWS C++ SDK throws "map:at" exception when Blob::GetProperties()/Blob::Download()  response doesn't contain "x-ms-creation-time" header.
https://github.com/Azure/azure-sdk-for-cpp/blob/main/sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/protocol/blob_rest_client.hpp#L6792
https://github.com/Azure/azure-sdk-for-cpp/blob/main/sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/protocol/blob_rest_client.hpp#L7151

The header is relatively new, and e.g. Azurite emulator doesn't return it (a bug on there side indeed):
https://github.com/Azure/Azurite/issues/963

As a workaround, I forced to use the patch below:
[0001-Let-GetProperties-Download-skip-x-ms-creation-time-h.patch.txt](https://github.com/Azure/azure-sdk-for-cpp/files/6950474/0001-Let-GetProperties-Download-skip-x-ms-creation-time-h.patch.txt)

Most likely I am not the only lucky one facing this issue; However I haven't found such issue in azure-sdk-for-cpp repository, so creating this new one. Presumably this should not be actually included in the SDK.  But to understand what had been happening, I had to build the debug-SDK and set a breakpoint for an exception (gdb: break _Unwind_RaiseException). 
map::at is extremely uninformative!

**Comment by Jinming-Hu** [comment] 2021-08-10 12:48
We've seen this kind of issues before. The problem is Azurite doesn't return some of the HTTP headers that it's supposed to return. So Azurite should fix the issue.

But there's indeed something we can do to help users better understand the reason for the failure. Adding an exception type is an option.

**Comment by Jinming-Hu** [comment] 2021-08-19 01:55
Azurite will fix this issue when this PR https://github.com/Azure/Azurite/pull/1007 is merged.

**Closed by Jinming-Hu** 2021-08-19 01:55 UTC
Labels: question, Client, customer-reported, Storage
