### ISSUE TITLE
Possible concurrency issue in storage queues

### ISSUE THREAD

**Issue by gearama** [Azure/azure-sdk-for-cpp#4436] opened 2023-03-10 22:35 UTC
valgrind --tool=drd ./azure-storage-queues-test &> ~/queues_thread.txt

[queues_thread.log](https://github.com/Azure/azure-sdk-for-cpp/files/10946700/queues_thread.log)

**Comment by Jinming-Hu** [comment] 2023-08-14 06:19
duplicate of https://github.com/Azure/azure-sdk-for-cpp/issues/4435

**Closed by Jinming-Hu** 2023-08-14 06:19 UTC
Labels: bug, Client, Storage
