### ISSUE TITLE
Requests delayed

### ISSUE THREAD

**Issue by RickWinter** [Azure/azure-sdk-for-cpp#2242] opened 2021-05-10 17:19 UTC
A small subsets of requests are taking longer than expected to navigate the pipeline.  This results in requests timing out.  Currently only being observed on Windows with libcurl.

**Comment by EmmaZhu** [comment] 2021-05-11 02:54
Hi @vhvb1989 

I got the issue on a Release-x64-static link built.  We have an application to upload/download files in high concurrency, repository is here: https://github.com/JasonYang-MSFT/azure-storage-data-movement, we don't have a very simple isolated repro, but I think the issue should be easy to reproduce with sending request to upload/download content with high concurrency. 

Thanks
Emma

**Comment by EmmaZhu** [comment] 2021-05-11 04:13
@vhvb1989 , I'm not sure whether it's relevant, but:
1. the issue happened when I ran our test about one day later.
2. I ran the test on a VM of Standard A3 (4 vcpus, 7 GiB memory) which is in the same DC with the test account.

**Comment by Jinming-Hu** [comment] 2021-05-11 05:18
Hi @EmmaZhu and @vhvb1989 , [azure-storage-data-movement](https://github.com/JasonYang-MSFT/azure-storage-data-movement) is kind of clunky, and it may not be ideal as a reproduction step.

I talked with Vincent, we believe it will be better if we write a small program that calls azure core transport layer directly (without going through storage sdk) and simulates the data access pattern of azure-storage-data-movement.

The data access pattern I can think of is (@EmmaZhu please add details if I missed any)

* use share key authentication
* concurrent upload and download of different sizes of blobs
* change the concurrency over the time

**Comment by RickWinter** [comment] 2021-05-12 16:16
@Jinming-Hu @EmmaZhu can you help us with the repro for this issue.

**Comment by vhvb1989** [comment] 2021-05-12 16:29
@Jinming-Hu @EmmaZhu please try reproduce again after pulling latest master with the leak-socket fix applied.

**Comment by vhvb1989** [comment] 2021-05-17 17:42
Closing based on email conversation:

Hi Victor,

I was suspecting that the issue was caused by No enough memory to allocate. In our testing application, there’s a memory cache which occupies large size of memory (almost the same with VM’s physical memory). I set the memory cache size limitation to a smaller value (2GB) and restarted the test again. The issue is not reproduced again yet. 

Thanks
Emma



Feel free to re-open if see it again

**Closed by vhvb1989** 2021-05-17 17:42 UTC
Labels: Client, Storage, blocking-release, bug
