### ISSUE TITLE
Add support for 100-continue in Azure Core

### ISSUE THREAD

**Issue by seanmcc-msft** [Azure/azure-sdk-for-cpp#4444] opened 2023-03-14 16:26 UTC
https://github.com/Azure/azure-sdk/issues/5787

**Comment by Jinming-Hu** [comment] 2023-03-15 01:47
We have two transports, libcurl and WinHTTP.

Libcurl already works in the way described in https://github.com/Azure/azure-sdk/issues/5787.
WinHTTP doesn't. I don't know if WinHTTP is able to do that.

**Comment by LarryOsterman** [comment] 2024-03-12 06:07
Duplicate of #3501

**Closed by LarryOsterman** 2024-03-12 06:07 UTC
Labels: feature-request, Azure.Core, Client
