### ISSUE TITLE
Live tests won't block the Release pipeline.

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk-for-cpp#2438] opened 2021-06-09 07:27 UTC
For a release pipeline, as soon as the unit tests are passed, the Review&Approve option becomes available even before the live tests are completed. If the pipeline is approved at that moment, the release will continue without the live tests completition.

**Comment by danieljurek** [comment] 2021-06-14 18:59
This is by design. Live tests (in most other languages) may run for several hours and a single failing test (potentially caused by issues not related to the quality of the SDK code) could block the release. While we want to provide live test information in unified pipelines ahead of release, we don't want those tests to block release. 

Instead we require that the build and "fast" tests (those which don't contact live services) must pass. The "fast" tests should be seen as more deterministic because they don't have to interact with live services.

**Comment by vhvb1989** [comment] 2021-06-14 19:14
@danieljurek can we change this for CPP?  In CPP we don't have record/playback for CI so we rely a LOT in the live tests for storage and KeyVault.  And in Core we also do some longer tests as part of live-tests.

the cpp live test won't take several hours.  

I would say, we really need this to avoid a potential regression to one release.  In the future, if we finally create the playback/record tests or unit test, we can then remove the live-tests dependency.

**Comment by danieljurek** [comment] 2021-06-17 18:15
Sounds good. We'll make this change.

**Comment by RickWinter** [comment] 2021-06-30 20:27
@danieljurek Is this blocked on anything?  Can it be committed and this issue closed

**Closed** 2021-06-30 22:22 UTC
Labels: Central-EngSys, bug
