### ISSUE TITLE
Add CI checks to ensure Notice.txt and cgmanifest.json stay in sync

### ISSUE THREAD

**Issue by RickWinter** [Azure/azure-sdk-for-cpp#3471] opened 2022-03-23 18:03 UTC
Add linting to validate our Notice.txt and cgmanifest.json stay in sync.

Stretch goal, verify the Notice.txt entries are still in use.

**Comment by kurtzeborn** [comment] 2022-06-27 20:34
Closing since this is a dupe of https://github.com/Azure/azure-sdk-tools/issues/3349 and the fix for that will be general to all languages.

**Closed by kurtzeborn** 2022-06-27 20:34 UTC
Labels: feature-request, EngSys, Central-EngSys
