### ISSUE TITLE
Fix documentation for Azure Core to avoid showing json lib internal components

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk-for-cpp#1621] opened 2021-02-06 06:43 UTC

**Comment by RickWinter** [comment] 2021-02-08 17:56
@vhvb1989 We should exclude this file from doc generation.  This is needed for the February release

**Comment by ahsonkhan** [comment] 2021-02-08 20:24
Duplicate of https://github.com/Azure/azure-sdk-for-cpp/issues/1576 (fyi)

**Closed** 2021-02-08 22:24 UTC
Labels: Azure.Core, Client, Docs, EngSys, blocking-release
