### ISSUE TITLE
Possible concurrency issues in storage blobs

### ISSUE THREAD

**Issue by gearama** [Azure/azure-sdk-for-cpp#4439] opened 2023-03-10 22:52 UTC
valgrind --tool=dr^C./azure-storage-blobs-test &> ~/blobs_thread.txt

[blobs_thread.log](https://github.com/Azure/azure-sdk-for-cpp/files/10946731/blobs_thread.log)

**Comment by Jinming-Hu** [comment] 2023-08-14 06:20
duplicate of https://github.com/Azure/azure-sdk-for-cpp/issues/4435

**Closed by Jinming-Hu** 2023-08-14 06:20 UTC
Labels: bug, Client, Storage
