### ISSUE TITLE
uploading failed on Windows

### ISSUE THREAD

**Issue by Jinming-Hu** [Azure/azure-sdk-for-cpp#815] opened 2020-10-20 07:11 UTC
I'm trying to upload a blob with 50000 blocks, each block is 4000MiB. The whole blob is about 200TB. After uploading about 2.6TB, the program crashed due to this exception

```
>azure-storage-sample BlobsGettingStarted
failed to upload, Error while sending request. Failed sending data to the peer
```

looks like this exception was thrown from transport layer. The VM and the storage account is in the same region, so the network is highly reliable and stable. I didn't find any network or storage service issue during that period. @vhvb1989 can core team help us understand why this exception was thrown?

**Comment by Jinming-Hu** [comment] 2020-10-20 07:12
i'm using latest master branch, commit a138551

**Comment by Jinming-Hu** [comment] 2020-10-20 07:12
looks like a different issue from https://github.com/Azure/azure-sdk-for-cpp/issues/814

**Comment by vhvb1989** [comment] 2020-10-20 16:40
That's libcurl reporting an error.
You might want to compile with libcurl verbose (uncomment this line: https://github.com/Azure/azure-sdk-for-cpp/blob/master/sdk/core/azure-core/src/http/curl/curl.cpp#L1071)  and compile.

You will see more info about the failure in the logs
*my guessing is that it is related to SSL.

Can you also share your source code?  
Also provide the CMake generate command you are using.

**Comment by Jinming-Hu** [comment] 2020-10-21 01:47
hi @vhvb1989 i'm going to give you an environment where we can reproduce this issue so that you can debug there.

**Comment by Jinming-Hu** [comment] 2020-10-23 01:31
failed again after uploading ~50TB

```
>azure-storage-sample BlobsGettingStarted
failed to upload, Error while sending request. Failed sending data to the peer
```

**Comment by Jinming-Hu** [comment] 2020-10-26 02:46
```
index c4c90fc..c97481e 100644
--- a/sdk/storage/azure-storage-common/src/storage_retry_policy.cpp
+++ b/sdk/storage/azure-storage-common/src/storage_retry_policy.cpp
@@ -5,6 +5,7 @@
 #include "azure/storage/common/storage_common.hpp"

 #include <thread>
+#include <iostream>

 namespace Azure { namespace Storage {

@@ -84,8 +85,9 @@ namespace Azure { namespace Storage {
           throw;
         }
       }
-      catch (Azure::Core::Http::TransportException const&)
+      catch (Azure::Core::Http::TransportException const& e)
       {
+        std::cout << "failed at retry " + std::to_string(i) + ", " + e.what() << std::endl;
         if (lastAttempt)
         {
           throw;
```


```
failed at retry 0, Error while reading from network socket. CURLE code: 56. Failure when receiving data from the peer
failed at retry 1, Error while reading from network socket. CURLE code: 56. Failure when receiving data from the peer
failed at retry 2, Error while reading from network socket. CURLE code: 56. Failure when receiving data from the peer
failed at retry 3, Error while reading from network socket. CURLE code: 56. Failure when receiving data from the peer
failed at retry 0, Error while reading from network socket. CURLE code: 56. Failure when receiving data from the peer
failed at retry 4, Error while reading from network socket. CURLE code: 56. Failure when receiving data from the peer
failed at retry 1, Error while reading from network socket. CURLE code: 56. Failure when receiving data from the peer
failed at retry 2, Error while reading from network socket. CURLE code: 56. Failure when receiving data from the peer
failed at retry 3, Error while reading from network socket. CURLE code: 56. Failure when receiving data from the peer
failed at retry 4, Error while reading from network socket. CURLE code: 56. Failure when receiving data from the peer
failed at retry 5, Error while reading from network socket. CURLE code: 56. Failure when receiving data from the peer
failed at retry 5, Error while reading from network socket. CURLE code: 56. Failure when receiving data from the peer
failed at retry 6, Error while sending request. Failed sending data to the peer
failed at retry 6, Error while sending request. Failed sending data to the peer
failed at retry 7, Error while sending request. Failed sending data to the peer
failed at retry 7, Error while sending request. Failed sending data to the peer
failed at retry 8, Error while sending request. Failed sending data to the peer
failed at retry 8, Error while sending request. Failed sending data to the peer
failed at retry 9, Error while sending request. Failed sending data to the peer
failed at retry 9, Error while sending request. Failed sending data to the peer
failed at retry 10, Error while sending request. Failed sending data to the peer
failed to upload, Error while sending request. Failed sending data to the peer
```

**Comment by Jinming-Hu** [comment] 2020-10-26 08:44
i'm able to reproduce the issue with the following code

```
  using namespace Azure::Storage::Blobs;

  std::string containerName = "sample-container";

  auto containerClient
      = BlobContainerClient::CreateFromConnectionString(YOUR_CONNECTION_STRING, containerName);
  try
  {
    containerClient.Create();
  }
  catch (std::runtime_error&)
  {
    // The container may already exist
  }

  std::atomic<int> counter{0};
  std::atomic<bool> failed{false};
  const int counterMax = 25000;

  auto upload_func = [&]() {
    while (true)
    {
      int i = counter.fetch_add(1);
      if (counter >= counterMax)
      {
        break;
      }
      if (failed)
      {
        break;
      }

      BlockBlobClient blobClient
          = containerClient.GetBlockBlobClient("sample-blob-" + std::to_string(i));
      UploadBlockBlobFromOptions options;
      options.ChunkSize = 4000 * 1024 * 1024ULL;
      try
      {
        blobClient.UploadFrom("C:/Users/jamis/Desktop/file_generated"); // 8000MiB file
        blobClient.Delete();
      }
      catch (std::runtime_error& e)
      {
        std::cout << std::to_string(i) + "failed, " + e.what() << std::endl;
        failed = true;
        return;
      }
      std::cout << i << std::endl;
    }
  };

  std::vector<std::thread> threadHandles;
  for (int i = 0; i < 48; ++i)
  {
    threadHandles.emplace_back(std::thread(upload_func));
  }
  for (auto& h : threadHandles)
  {
    h.join();
  }
```

Generate a 8000MiB(8000 * 1024 * 1024 bytes) file and fill the path in the code snippet.

env:

Azure VM: Standard H16mr_Promo (16 vcpus, 224 GiB memory)
Storage Account: Standard StorageV2 (general purpose v2) LRS in the same region as the VM
Compiler: VS 2019 Release build

**Comment by Jinming-Hu** [comment] 2020-10-27 01:45
@vhvb1989 Storage team thinks this issue is kind of severe thus blocking our Nov. release. Can you prioritize this one?

**Comment by vhvb1989** [comment] 2020-10-27 06:03
@Jinming-Hu  can you please try to reproduce with this branch
https://github.com/Azure/azure-sdk-for-cpp/pull/863

Let me know if this solves the issue.
II am guessing, for your test source code, that a upload operation is failing (I/O fail) because you are increasing the size of the chunk to much. The bigger the chunk, the more probabilities you have for I/O fails).

I was looking into the code and if this ever happen, the connection is still moved to the pool and reused (hence failed).  
I am adding a fix for this.

Let me know if it works

**Closed** 2020-10-28 08:27 UTC
Labels: Azure.Core, Client, blocking-release, bug
