### ISSUE TITLE
latest master branch cannot build

### ISSUE THREAD

**Issue by Jinming-Hu** [Azure/azure-sdk-for-cpp#739] opened 2020-10-12 02:39 UTC
I think the build failures are introduced in this commit https://github.com/Azure/azure-sdk-for-cpp/commit/cd2a8a3812725c3524e5d5fd1ab49b9cb08e0890

it says `If no option is explicitly added, curl will be used for POSIX and WIN HTTP for WIndows `. But actually it doesn't work. Did you try it before merge the PR?

**Comment by Jinming-Hu** [comment] 2020-10-12 03:53
On Windows, if I run the following command in `build/` directory

```
cmake .. -A x64 -DCMAKE_TOOLCHAIN_FILE=C:/ProgramFiles/vcpkg/scripts/buildsystems/vcpkg.cmake -DBUILD_TESTING=ON
cmake --build .
```

I got the following errors

```
Microsoft (R) Build Engine version 16.7.0+b89cb5fde for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  Checking Build System
  Building Custom Rule C:/Users/jinmhu.FAREAST/Desktop/azure-sdk-for-cpp/sdk/core/azure-core/CMakeLists.txt
  Not using Vcpkg because VcpkgEnabled is "false"
  context.cpp
  credentials.cpp
C:\Users\jinmhu.FAREAST\Desktop\azure-sdk-for-cpp\sdk\core\azure-core\src\credentials\credentials.cpp(83,77): error C20
39: 'CurlTransport': is not a member of 'Azure::Core::Http' [C:\Users\jinmhu.FAREAST\Desktop\azure-sdk-for-cpp\build\sd
k\core\azure-core\azure-core.vcxproj]
C:\Users\jinmhu.FAREAST\Desktop\azure-sdk-for-cpp\sdk\core\azure-core\inc\azure/core/http/pipeline.hpp(19): message : s
ee declaration of 'Azure::Core::Http' [C:\Users\jinmhu.FAREAST\Desktop\azure-sdk-for-cpp\build\sdk\core\azure-core\azur
e-core.vcxproj]
C:\Users\jinmhu.FAREAST\Desktop\azure-sdk-for-cpp\sdk\core\azure-core\src\credentials\credentials.cpp(83,90): error C20
65: 'CurlTransport': undeclared identifier [C:\Users\jinmhu.FAREAST\Desktop\azure-sdk-for-cpp\build\sdk\core\azure-core
\azure-core.vcxproj]
C:\Users\jinmhu.FAREAST\Desktop\azure-sdk-for-cpp\sdk\core\azure-core\src\credentials\credentials.cpp(83,59): error C26
72: 'std::make_unique': no matching overloaded function found [C:\Users\jinmhu.FAREAST\Desktop\azure-sdk-for-cpp\build\
sdk\core\azure-core\azure-core.vcxproj]
C:\Users\jinmhu.FAREAST\Desktop\azure-sdk-for-cpp\sdk\core\azure-core\src\credentials\credentials.cpp(83,92): error C29
74: 'std::make_unique': invalid template argument for '_Ty', type expected [C:\Users\jinmhu.FAREAST\Desktop\azure-sdk-f
or-cpp\build\sdk\core\azure-core\azure-core.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\include\memory(2708): message :
 see declaration of 'std::make_unique' [C:\Users\jinmhu.FAREAST\Desktop\azure-sdk-for-cpp\build\sdk\core\azure-core\azu
re-core.vcxproj]
  policies.cpp
  datetime.cpp
  body_stream.cpp
  http.cpp
  logging_policy.cpp
  policy.cpp
  raw_response.cpp
  request.cpp
  retry_policy.cpp
  telemetry_policy.cpp
  transport_policy.cpp
  url.cpp
  logging.cpp
  strings.cpp
  version.cpp
  Compiling...
  Generating Code...
  Building Custom Rule C:/Users/jinmhu.FAREAST/Desktop/azure-sdk-for-cpp/build/_deps/googletest-src/googletest/CMakeLis
  ts.txt
  Not using Vcpkg because VcpkgEnabled is "false"
  gtest-all.cc
  gtest.vcxproj -> C:\Users\jinmhu.FAREAST\Desktop\azure-sdk-for-cpp\build\lib\Debug\gtestd.lib
  Building Custom Rule C:/Users/jinmhu.FAREAST/Desktop/azure-sdk-for-cpp/build/_deps/googletest-src/googlemock/CMakeLis
  ts.txt
  Not using Vcpkg because VcpkgEnabled is "false"
  gtest-all.cc
  gmock-all.cc
  Generating Code...
  gmock.vcxproj -> C:\Users\jinmhu.FAREAST\Desktop\azure-sdk-for-cpp\build\lib\Debug\gmockd.lib
  Building Custom Rule C:/Users/jinmhu.FAREAST/Desktop/azure-sdk-for-cpp/build/_deps/googletest-src/googletest/CMakeLis
  ts.txt
  Not using Vcpkg because VcpkgEnabled is "false"
  gtest_main.cc
  gtest_main.vcxproj -> C:\Users\jinmhu.FAREAST\Desktop\azure-sdk-for-cpp\build\lib\Debug\gtest_maind.lib
  Building Custom Rule C:/Users/jinmhu.FAREAST/Desktop/azure-sdk-for-cpp/sdk/template/azure-template/CMakeLists.txt
  Not using Vcpkg because VcpkgEnabled is "false"
  version.cpp
  template_client.cpp
  Compiling...
  Generating Code...
  azure-template.vcxproj -> C:\Users\jinmhu.FAREAST\Desktop\azure-sdk-for-cpp\build\sdk\template\azure-template\Debug\a
  zure-template.lib
  Building Custom Rule C:/Users/jinmhu.FAREAST/Desktop/azure-sdk-for-cpp/sdk/template/azure-template/test/CMakeLists.tx
  t
  Not using Vcpkg because VcpkgEnabled is "false"
  template_test.cpp
  azure-template-test.vcxproj -> C:\Users\jinmhu.FAREAST\Desktop\azure-sdk-for-cpp\build\sdk\template\azure-template\te
  st\Debug\azure-template-test.exe
```

**Comment by Jinming-Hu** [comment] 2020-10-12 03:56
On Windows, if I run the following command in build/ directory

```
cmake .. -A x64 -DCMAKE_TOOLCHAIN_FILE=C:/ProgramFiles/vcpkg/scripts/buildsystems/vcpkg.cmake -DBUILD_TESTING=ON -DBUILD_TRANSPORT_WINHTTP=ON
cmake --build .
```

I got the following errors

```
Microsoft (R) Build Engine version 16.7.0+b89cb5fde for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  Checking Build System
  Building Custom Rule C:/Users/jinmhu.FAREAST/Desktop/azure-sdk-for-cpp/sdk/core/azure-core/CMakeLists.txt
  Not using Vcpkg because VcpkgEnabled is "false"
  context.cpp
  credentials.cpp
C:\Users\jinmhu.FAREAST\Desktop\azure-sdk-for-cpp\sdk\core\azure-core\src\credentials\credentials.cpp(83,77): error C20
39: 'CurlTransport': is not a member of 'Azure::Core::Http' [C:\Users\jinmhu.FAREAST\Desktop\azure-sdk-for-cpp\build\sd
k\core\azure-core\azure-core.vcxproj]
C:\Users\jinmhu.FAREAST\Desktop\azure-sdk-for-cpp\sdk\core\azure-core\inc\azure/core/http/pipeline.hpp(19): message : s
ee declaration of 'Azure::Core::Http' [C:\Users\jinmhu.FAREAST\Desktop\azure-sdk-for-cpp\build\sdk\core\azure-core\azur
e-core.vcxproj]
C:\Users\jinmhu.FAREAST\Desktop\azure-sdk-for-cpp\sdk\core\azure-core\src\credentials\credentials.cpp(83,90): error C20
65: 'CurlTransport': undeclared identifier [C:\Users\jinmhu.FAREAST\Desktop\azure-sdk-for-cpp\build\sdk\core\azure-core
\azure-core.vcxproj]
C:\Users\jinmhu.FAREAST\Desktop\azure-sdk-for-cpp\sdk\core\azure-core\src\credentials\credentials.cpp(83,59): error C26
72: 'std::make_unique': no matching overloaded function found [C:\Users\jinmhu.FAREAST\Desktop\azure-sdk-for-cpp\build\
sdk\core\azure-core\azure-core.vcxproj]
C:\Users\jinmhu.FAREAST\Desktop\azure-sdk-for-cpp\sdk\core\azure-core\src\credentials\credentials.cpp(83,92): error C29
74: 'std::make_unique': invalid template argument for '_Ty', type expected [C:\Users\jinmhu.FAREAST\Desktop\azure-sdk-f
or-cpp\build\sdk\core\azure-core\azure-core.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\include\memory(2708): message :
 see declaration of 'std::make_unique' [C:\Users\jinmhu.FAREAST\Desktop\azure-sdk-for-cpp\build\sdk\core\azure-core\azu
re-core.vcxproj]
  policies.cpp
  datetime.cpp
  body_stream.cpp
  http.cpp
  logging_policy.cpp
  policy.cpp
  raw_response.cpp
  request.cpp
  retry_policy.cpp
  telemetry_policy.cpp
  transport_policy.cpp
  url.cpp
  logging.cpp
  strings.cpp
  version.cpp
  Compiling...
  Generating Code...
  Building Custom Rule C:/Users/jinmhu.FAREAST/Desktop/azure-sdk-for-cpp/build/_deps/googletest-src/googletest/CMakeLis
  ts.txt
  Not using Vcpkg because VcpkgEnabled is "false"
  gtest-all.cc
  gtest.vcxproj -> C:\Users\jinmhu.FAREAST\Desktop\azure-sdk-for-cpp\build\lib\Debug\gtestd.lib
  Building Custom Rule C:/Users/jinmhu.FAREAST/Desktop/azure-sdk-for-cpp/build/_deps/googletest-src/googlemock/CMakeLis
  ts.txt
  Not using Vcpkg because VcpkgEnabled is "false"
  gtest-all.cc
  gmock-all.cc
  Generating Code...
  gmock.vcxproj -> C:\Users\jinmhu.FAREAST\Desktop\azure-sdk-for-cpp\build\lib\Debug\gmockd.lib
  Building Custom Rule C:/Users/jinmhu.FAREAST/Desktop/azure-sdk-for-cpp/build/_deps/googletest-src/googletest/CMakeLis
  ts.txt
  Not using Vcpkg because VcpkgEnabled is "false"
  gtest_main.cc
  gtest_main.vcxproj -> C:\Users\jinmhu.FAREAST\Desktop\azure-sdk-for-cpp\build\lib\Debug\gtest_maind.lib
  Building Custom Rule C:/Users/jinmhu.FAREAST/Desktop/azure-sdk-for-cpp/sdk/template/azure-template/CMakeLists.txt
  Not using Vcpkg because VcpkgEnabled is "false"
  version.cpp
  template_client.cpp
  Compiling...
  Generating Code...
  azure-template.vcxproj -> C:\Users\jinmhu.FAREAST\Desktop\azure-sdk-for-cpp\build\sdk\template\azure-template\Debug\a
  zure-template.lib
  Building Custom Rule C:/Users/jinmhu.FAREAST/Desktop/azure-sdk-for-cpp/sdk/template/azure-template/test/CMakeLists.tx
  t
  Not using Vcpkg because VcpkgEnabled is "false"
  template_test.cpp
  azure-template-test.vcxproj -> C:\Users\jinmhu.FAREAST\Desktop\azure-sdk-for-cpp\build\sdk\template\azure-template\te
  st\Debug\azure-template-test.exe
```

**Comment by Jinming-Hu** [comment] 2020-10-12 03:58
but the following command works

```
cmake .. -A x64 -DCMAKE_TOOLCHAIN_FILE=C:/ProgramFiles/vcpkg/scripts/buildsystems/vcpkg.cmake -DBUILD_TESTING=ON -DBUILD_TRANSPORT_CURL=ON
```

**Comment by vhvb1989** [comment] 2020-10-12 17:40
This is expected behavior.
It is currently failing because we don't have winHttp adapter yet (see #354 ).
If you want to use CURL on Windows you have to explicitly ask for it.
This issue will be fixed once winHttp adapter is merged to master.

Look how CI legs are currently explicitly building CURL on Windows for now.

Assigning to @ahsonkhan as part of winhttp

**Comment by ahsonkhan** [comment] 2020-10-12 22:11
@vhvb1989, in the meantime, can we make it so the default build command works as expected and only uses curl for all OS (so that the repo continues to build)? We should try to avoid breaking documented build steps while some feature is in progress/not ready.

**Comment by vhvb1989** [comment] 2020-10-12 22:56
> 
> 
> @vhvb1989, in the meantime, can we make it so the default build command works as expected and only uses curl for all OS (so that the repo continues to build)? We should try to avoid breaking documented build steps while some feature is in progress/not ready.

Since the winhttp is on your queue, I would let you decide if you want to have this workaround for now.
It makes more sense to me to fail compilation when we are expecting something that is missing than injecting curl.

But, I would let you choose.
Here is a PR you can use to introduce the Workaround.
https://github.com/Azure/azure-sdk-for-cpp/pull/753

**Closed** 2020-10-14 19:15 UTC
Labels: Azure.Core, Client, blocking-release, bug
