### ISSUE TITLE
azure-core testcase hang issue

### ISSUE THREAD

**Issue by JinmingHu-MSFT** [Azure/azure-sdk-for-cpp#455] opened 2020-08-14 06:56 UTC
i've seen this many times
```
Updating test list for fixtures
Added 0 tests to meet fixture requirements
Checking test dependency graph...
Checking test dependency graph end
test 1
    Start 1: azure-core-test

1: Test command: D:\a\1\s\build\sdk\core\azure-core\test\ut\Debug\azure-core-test.exe
1: Test timeout computed to be: 10000000
1: [==========] Running 39 tests from 7 test suites.
1: [----------] Global test environment set-up.
1: [----------] 21 tests from TransportAdapter
1: [ RUN      ] TransportAdapter.customSizePutFromFile
1: [       OK ] TransportAdapter.customSizePutFromFile (56 ms)
1: [ RUN      ] TransportAdapter.customSizePutFromFileDefault
1: [       OK ] TransportAdapter.customSizePutFromFileDefault (46 ms)
1: [ RUN      ] TransportAdapter.customSizePutFromFileBiggerPage
1: [       OK ] TransportAdapter.customSizePutFromFileBiggerPage (35 ms)
1: [ RUN      ] TransportAdapter.get
1: [       OK ] TransportAdapter.get (35 ms)
1: [ RUN      ] TransportAdapter.get204
1: [       OK ] TransportAdapter.get204 (23 ms)
1: [ RUN      ] TransportAdapter.getLoop
1: [       OK ] TransportAdapter.getLoop (415 ms)
1: [ RUN      ] TransportAdapter.head
1: [       OK ] TransportAdapter.head (32 ms)
1: [ RUN      ] TransportAdapter.put
1: [       OK ] TransportAdapter.put (23 ms)
1: [ RUN      ] TransportAdapter.deleteRequest
1: [       OK ] TransportAdapter.deleteRequest (10 ms)
1: [ RUN      ] TransportAdapter.patch
1: [       OK ] TransportAdapter.patch (19 ms)
1: [ RUN      ] TransportAdapter.getChunk
1: [       OK ] TransportAdapter.getChunk (1302 ms)
1: [ RUN      ] TransportAdapter.getWithStream
1: [       OK ] TransportAdapter.getWithStream (46 ms)
1: [ RUN      ] TransportAdapter.getLoopWithStream
1: [       OK ] TransportAdapter.getLoopWithStream (430 ms)
1: [ RUN      ] TransportAdapter.headWithStream
1: [       OK ] TransportAdapter.headWithStream (20 ms)
1: [ RUN      ] TransportAdapter.putWithStream
1: [       OK ] TransportAdapter.putWithStream (25 ms)
1: [ RUN      ] TransportAdapter.deleteRequestWithStream
1: [       OK ] TransportAdapter.deleteRequestWithStream (27 ms)
1: [ RUN      ] TransportAdapter.patchWithStream
1: [       OK ] TransportAdapter.patchWithStream (23 ms)
1: [ RUN      ] TransportAdapter.getChunkWithStream
1: [       OK ] TransportAdapter.getChunkWithStream (1296 ms)
1: [ RUN      ] TransportAdapter.createResponseT
1: [       OK ] TransportAdapter.createResponseT (27 ms)
1: [ RUN      ] TransportAdapter.customSizePut
1: [       OK ] TransportAdapter.customSizePut (170 ms)
1: [ RUN      ] TransportAdapter.putWithStreamOnFail
```

unittest hangs at `TransportAdapter.putWithStreamOnFail`

**Comment by RickWinter** [comment] 2020-08-14 15:57
@JinmingHu-MSFT Can you attach the test output and callstack.

**Comment by JinmingHu-MSFT** [comment] 2020-08-15 04:48
i'll reopen this next time I encounter it.

**Comment by JinmingHu-MSFT** [comment] 2020-08-16 13:39
[Pipelines Result](https://dev.azure.com/azure-sdk/public/_build/results?buildId=497492&view=logs&j=5f43df56-f144-584b-8cac-2916b6897a0a&t=14d35044-48e5-5798-2139-bf681fde4f6c&l=49)
[Raw log](https://dev.azure.com/azure-sdk/29ec6040-b234-4e31-b139-33dc4287b756/_apis/build/builds/497492/logs/141)
```
2020-08-16T02:27:05.4716433Z ##[section]Starting: ctest
2020-08-16T02:27:05.5051052Z ==============================================================================
2020-08-16T02:27:05.5052420Z Task         : Command line
2020-08-16T02:27:05.5053043Z Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
2020-08-16T02:27:05.5053754Z Version      : 2.164.2
2020-08-16T02:27:05.5054051Z Author       : Microsoft Corporation
2020-08-16T02:27:05.5054476Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
2020-08-16T02:27:05.5055055Z ==============================================================================
2020-08-16T02:27:06.8945378Z Generating script.
2020-08-16T02:27:06.9231648Z Script contents:
2020-08-16T02:27:06.9350298Z ctest -V --tests-regex azure-core
2020-08-16T02:27:06.9808851Z ========================== Starting Command Output ===========================
2020-08-16T02:27:07.0344630Z ##[command]"C:\windows\system32\cmd.exe" /D /E:ON /V:OFF /S /C "CALL "D:\a\_temp\001e5e17-5d4e-4116-9bd7-4ffafa4f2935.cmd""
2020-08-16T02:27:07.8958117Z UpdateCTestConfiguration  from :D:/a/1/s/build/DartConfiguration.tcl
2020-08-16T02:27:08.0277532Z UpdateCTestConfiguration  from :D:/a/1/s/build/DartConfiguration.tcl
2020-08-16T02:27:08.0330119Z Test project D:/a/1/s/build
2020-08-16T02:27:08.0342550Z Constructing a list of tests
2020-08-16T02:27:08.0516536Z Done constructing a list of tests
2020-08-16T02:27:08.0517513Z Updating test list for fixtures
2020-08-16T02:27:08.0518365Z Added 0 tests to meet fixture requirements
2020-08-16T02:27:08.0723978Z Checking test dependency graph...
2020-08-16T02:27:08.0726098Z Checking test dependency graph end
2020-08-16T02:27:08.0727617Z test 1
2020-08-16T02:27:08.0733345Z     Start 1: azure-core-test
2020-08-16T02:27:08.0739703Z 
2020-08-16T02:27:08.0740782Z 1: Test command: D:\a\1\s\build\sdk\core\azure-core\test\ut\Debug\azure-core-test.exe
2020-08-16T02:27:08.0741788Z 1: Test timeout computed to be: 10000000
2020-08-16T02:27:08.3773759Z 1: [==========] Running 47 tests from 8 test suites.
2020-08-16T02:27:08.3775215Z 1: [----------] Global test environment set-up.
2020-08-16T02:27:08.3775943Z 1: [----------] 21 tests from TransportAdapter
2020-08-16T02:27:08.3776747Z 1: [ RUN      ] TransportAdapter.customSizePutFromFile
2020-08-16T02:27:09.0413426Z 1: [       OK ] TransportAdapter.customSizePutFromFile (667 ms)
2020-08-16T02:27:09.0414805Z 1: [ RUN      ] TransportAdapter.customSizePutFromFileDefault
2020-08-16T02:27:09.6594393Z 1: [       OK ] TransportAdapter.customSizePutFromFileDefault (619 ms)
2020-08-16T02:27:09.6595857Z 1: [ RUN      ] TransportAdapter.customSizePutFromFileBiggerPage
2020-08-16T02:27:10.2856005Z 1: [       OK ] TransportAdapter.customSizePutFromFileBiggerPage (625 ms)
2020-08-16T02:27:10.2857273Z 1: [ RUN      ] TransportAdapter.get
2020-08-16T02:27:10.5727530Z 1: [       OK ] TransportAdapter.get (287 ms)
2020-08-16T02:27:10.5729450Z 1: [ RUN      ] TransportAdapter.get204
2020-08-16T02:27:10.6176882Z 1: [       OK ] TransportAdapter.get204 (45 ms)
2020-08-16T02:27:10.6178140Z 1: [ RUN      ] TransportAdapter.getLoop
2020-08-16T02:27:13.5755485Z 1: [       OK ] TransportAdapter.getLoop (2957 ms)
2020-08-16T02:27:13.5756675Z 1: [ RUN      ] TransportAdapter.head
2020-08-16T02:27:13.7131755Z 1: [       OK ] TransportAdapter.head (137 ms)
2020-08-16T02:27:13.7133600Z 1: [ RUN      ] TransportAdapter.put
2020-08-16T02:27:13.9181447Z 1: [       OK ] TransportAdapter.put (205 ms)
2020-08-16T02:27:13.9182556Z 1: [ RUN      ] TransportAdapter.deleteRequest
2020-08-16T02:27:14.0610364Z 1: [       OK ] TransportAdapter.deleteRequest (143 ms)
2020-08-16T02:27:14.0611428Z 1: [ RUN      ] TransportAdapter.patch
2020-08-16T02:27:14.2092808Z 1: [       OK ] TransportAdapter.patch (148 ms)
2020-08-16T02:27:14.2094004Z 1: [ RUN      ] TransportAdapter.getChunk
2020-08-16T02:27:15.6607148Z 1: [       OK ] TransportAdapter.getChunk (1452 ms)
2020-08-16T02:27:15.6609154Z 1: [ RUN      ] TransportAdapter.getWithStream
2020-08-16T02:27:15.9629359Z 1: [       OK ] TransportAdapter.getWithStream (302 ms)
2020-08-16T02:27:15.9631619Z 1: [ RUN      ] TransportAdapter.getLoopWithStream
2020-08-16T02:27:18.8472659Z 1: [       OK ] TransportAdapter.getLoopWithStream (2884 ms)
2020-08-16T02:27:18.9897127Z 1: [ RUN      ] TransportAdapter.headWithStream
2020-08-16T02:27:18.9899135Z 1: [       OK ] TransportAdapter.headWithStream (143 ms)
2020-08-16T02:27:18.9899976Z 1: [ RUN      ] TransportAdapter.putWithStream
2020-08-16T02:27:19.1984603Z 1: [       OK ] TransportAdapter.putWithStream (209 ms)
2020-08-16T02:27:19.1986285Z 1: [ RUN      ] TransportAdapter.deleteRequestWithStream
2020-08-16T02:27:19.3488722Z 1: [       OK ] TransportAdapter.deleteRequestWithStream (150 ms)
2020-08-16T02:27:19.3490689Z 1: [ RUN      ] TransportAdapter.patchWithStream
2020-08-16T02:27:19.4948735Z 1: [       OK ] TransportAdapter.patchWithStream (146 ms)
2020-08-16T02:27:19.4960305Z 1: [ RUN      ] TransportAdapter.getChunkWithStream
2020-08-16T02:27:20.8926843Z 1: [       OK ] TransportAdapter.getChunkWithStream (1398 ms)
2020-08-16T02:27:20.8928371Z 1: [ RUN      ] TransportAdapter.createResponseT
2020-08-16T02:27:21.0392738Z 1: [       OK ] TransportAdapter.createResponseT (146 ms)
2020-08-16T02:27:21.0395836Z 1: [ RUN      ] TransportAdapter.customSizePut
2020-08-16T02:27:22.1509944Z 1: [       OK ] TransportAdapter.customSizePut (1112 ms)
2020-08-16T02:27:22.1511097Z 1: [ RUN      ] TransportAdapter.putWithStreamOnFail
2020-08-16T03:07:02.3836133Z Terminate batch job (Y/N)? 
2020-08-16T03:07:02.5973523Z ^C
2020-08-16T03:07:02.8611456Z ##[error]The operation was canceled.
2020-08-16T03:07:02.8641006Z ##[section]Finishing: ctest
```

**Comment by JinmingHu-MSFT** [comment] 2020-08-16 13:40
This is not a crash issue, so there's no callstack. it's a hang issue.

**Comment by JinmingHu-MSFT** [comment] 2020-08-18 05:58
here's another one https://dev.azure.com/azure-sdk/internal/_build/results?buildId=499192&view=logs&jobId=becb4c78-6d46-5b40-696d-491037a3748a&j=becb4c78-6d46-5b40-696d-491037a3748a&t=7da4ec77-80ef-5cae-b212-17e17d7c0a17

**Comment by JinmingHu-MSFT** [comment] 2020-08-27 06:05
this is a potential bug in Core HTTP Client. I can reproduce this issue on both Linux and Windows. Run azure-core-test with `--gtest_filter=TransportAdapter.putWithStreamOnFail --gtest_repeat=3`. It always hangs at the second time.

**Comment by JinmingHu-MSFT** [comment] 2020-08-27 06:14
The server closes the connection after the first request. There must be something wrong with connection reuse.

```
$ curl -X PUT "http://httpbin.org/get" --data-binary "@file" --next -X PUT "http://httpbin.org/get" --data-binary "@file" -v
*   Trying 3.220.112.94...
* TCP_NODELAY set
* Connected to httpbin.org (3.220.112.94) port 80 (#0)
> PUT /get HTTP/1.1
> Host: httpbin.org
> User-Agent: curl/7.54.0
> Accept: */*
> Content-Length: 1024
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 1024 out of 1024 bytes
< HTTP/1.1 405 METHOD NOT ALLOWED
< Date: Thu, 27 Aug 2020 06:11:32 GMT
< Content-Type: text/html
< Content-Length: 178
< Connection: keep-alive
< Server: gunicorn/19.9.0
< Allow: GET, OPTIONS, HEAD
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Credentials: true
< 
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>405 Method Not Allowed</title>
<h1>Method Not Allowed</h1>
<p>The method is not allowed for the requested URL.</p>
* Connection #0 to host httpbin.org left intact
* Found bundle for host httpbin.org: 0x7fd5c8e0cd00 [can pipeline]
* Connection 0 seems to be dead!
* Closing connection 0
* Hostname httpbin.org was found in DNS cache
*   Trying 3.220.112.94...
* TCP_NODELAY set
* Connected to httpbin.org (3.220.112.94) port 80 (#1)
> PUT /get HTTP/1.1
> Host: httpbin.org
> User-Agent: curl/7.54.0
> Accept: */*
> Content-Length: 1024
> Content-Type: application/x-www-form-urlencoded
> 
* upload completely sent off: 1024 out of 1024 bytes
< HTTP/1.1 405 METHOD NOT ALLOWED
< Date: Thu, 27 Aug 2020 06:11:33 GMT
< Content-Type: text/html
< Content-Length: 178
< Connection: keep-alive
< Server: gunicorn/19.9.0
< Allow: GET, OPTIONS, HEAD
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Credentials: true
< 
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>405 Method Not Allowed</title>
<h1>Method Not Allowed</h1>
<p>The method is not allowed for the requested URL.</p>
* Connection #1 to host httpbin.org left intact
```

**Comment by JinmingHu-MSFT** [comment] 2020-08-27 08:55
the issue is gone, cannot reproduce anymore

**Comment by JinmingHu-MSFT** [comment] 2020-08-27 09:36
A program that can reproduce this issue

```
#include <iostream>
#include <memory>
#include <vector>

#include "azure/core/http/curl/curl.hpp"
#include "azure/core/http/http.hpp"
#include "azure/core/http/pipeline.hpp"


int main() {
  using namespace Azure::Core;
  using namespace Azure::Core::Http;
  using namespace std;

  std::string host("http://httpbin.org/get");

  for (int i = 0; i < 10; ++i)
  {
    std::cout << "i == " << i << std::endl;
    // Create the Transport
    std::shared_ptr<HttpTransport> transport = std::make_unique<CurlTransport>();

    std::vector<std::unique_ptr<HttpPolicy>> policies;

    // Add the transport policy
    policies.push_back(std::make_unique<TransportPolicy>(std::move(transport)));

    auto httpPipeline = Http::HttpPipeline(policies);

    auto context = Azure::Core::GetApplicationContext();

    // PUT 1k
    auto requestBodyVector = std::vector<uint8_t>(1024, 'x');
    auto bodyRequest = Azure::Core::Http::MemoryBodyStream(requestBodyVector);
    auto request
        = Azure::Core::Http::Request(Azure::Core::Http::HttpMethod::Put, host, &bodyRequest, true);
    auto response = httpPipeline.Send(context, request);
    std::cout << "i == " << i << std::endl;
  }

}

```

**Comment by vhvb1989** [comment] 2020-08-27 17:03
@JinmingHu-MSFT , the issue in the provided test program is that the host url is `http://httpbin.org/get`
That url accepts GET.
Then you make a POST to that url.

I will take a look to see how we can protect the code from the hanging.

**Comment by vhvb1989** [comment] 2020-08-27 17:37
The issue is that Server closes the channel when the response is an Error.
Then next request was trying to re-use the same connection which was closed and it has hanging waiting for the socket to be writable.
Created PR to fix

**Comment by vhvb1989** [comment] 2020-08-28 00:52
There were 2 issue here.
One is fixed with the related PR.

For the other one I have created: https://github.com/Azure/azure-sdk-for-cpp/issues/550
It is a similar issue but requires more coding to be resolved.  I am disabling the test case that might be showing this issue.

**Comment by katmsft** [comment] 2020-08-28 13:29
Hi Victor, thanks for the fix, however, there is still some reoccurrence of the issue during our validation process and I will try to reproduce it with dummy PR and let you know about it.

**Comment by katmsft** [comment] 2020-08-28 14:33
https://github.com/Azure/azure-sdk-for-cpp/pull/556, please see the CI of this dummy PR, reproduces the issue.

**Comment by vhvb1989** [comment] 2020-08-28 17:41
Thank you @katmsft .  In this new case, it is a test issue.
I have a new PR with changes to the test: https://github.com/Azure/azure-sdk-for-cpp/issues/557

It might happen that in some cases, the time we were waiting for the cleaner to finish was not enough because it was already running from previous tests.
I moved this special test to be the first one so I don't need to increase the time too much.

**Closed** 2020-08-28 23:17 UTC
Labels: Azure.Core, Client, blocking-release, bug
