### ISSUE TITLE
Intermittent AMQP SenderSendAsync test failure on windows - SEH exception with code 0xc0000005 thrown

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#4761] opened 2023-07-06 18:35 UTC
From an unrelated PR:

`Build Validate Win2022_Win32Api_debug_tests_x64`
https://dev.azure.com/azure-sdk/public/_build/results?buildId=2897004&view=logs&jobId=62f96420-69e0-55c5-87e4-47c3c06a1c78&j=62f96420-69e0-55c5-87e4-47c3c06a1c78&t=b3dd4564-7772-55ea-46bb-692a63de5bb4

```text
2023-07-06T18:00:48.5892492Z test 600
2023-07-06T18:00:48.5893134Z         Start 600: azure-core-amqp.TestMessages.SenderSendAsync
2023-07-06T18:00:48.5893520Z 
2023-07-06T18:00:48.5894210Z 600: Test command: D:\a\_work\1\s\build\sdk\core\azure-core-amqp\test\ut\Debug\azure-core-amqp-tests.exe "--gtest_filter=TestMessages.SenderSendAsync" "--gtest_also_run_disabled_tests"
2023-07-06T18:00:48.5894885Z 600: Working Directory: D:/a/_work/1/s/build/sdk/core/azure-core-amqp/test/ut
2023-07-06T18:00:48.5895355Z 600: Test timeout computed to be: 10000000
2023-07-06T18:00:48.5979577Z 600: Note: Google Test filter = TestMessages.SenderSendAsync
2023-07-06T18:00:48.5980225Z 600: [==========] Running 1 test from 1 test suite.
2023-07-06T18:00:48.5980873Z 600: [----------] Global test environment set-up.
2023-07-06T18:00:48.5981430Z 600: [----------] 1 test from TestMessages
2023-07-06T18:00:48.5981844Z 600: [ RUN      ] TestMessages.SenderSendAsync
2023-07-06T18:00:48.6008210Z 600: 
2023-07-06T18:00:48.6009486Z 600: [  INFO ] D:\a\_work\1\s\sdk\core\azure-core-amqp\test\ut\session_tests.cpp(119):: Trying Test port: 5000
2023-07-06T18:00:48.6013676Z 600: 
2023-07-06T18:00:48.6014459Z 600: [  INFO ] D:\a\_work\1\s\sdk\core\azure-core-amqp\test\ut\message_sender_receiver.cpp(451):: Test port: 5000
2023-07-06T18:00:48.6015456Z 600: [2023-07-06T18:00:48.6013332Z] INFO  : Unknown port specified, assuming socket connection transport.
2023-07-06T18:00:48.6016648Z 600: [2023-07-06T18:00:48.6014717Z] DEBUG : Create socket transport for host localhost port: 5000
2023-07-06T18:00:48.6023553Z 600: 
2023-07-06T18:00:48.6024501Z 600: [  INFO ] D:\a\_work\1\s\sdk\core\azure-core-amqp\test\ut\message_sender_receiver.cpp(506):: MessageSenderEvents::OnMessageSenderSTateChanged.
2023-07-06T18:01:03.6019523Z 600: 
2023-07-06T18:01:03.6020861Z 600: [  INFO ] D:\a\_work\1\s\sdk\core\azure-core-amqp\test\ut\message_sender_receiver.cpp(484):: Message receiver opened, waiting for incoming message.
2023-07-06T18:01:03.6021363Z 600: 
2023-07-06T18:01:03.6021951Z 600: [  INFO ] D:\a\_work\1\s\sdk\core\azure-core-amqp\test\ut\message_sender_receiver.cpp(487):: Received incoming message!!
2023-07-06T18:01:19.4747073Z 600: 
2023-07-06T18:01:19.4748978Z 600: [  INFO ] D:\a\_work\1\s\sdk\core\azure-core-amqp\test\ut\message_sender_receiver.cpp(506):: MessageSenderEvents::OnMessageSenderSTateChanged.
2023-07-06T18:01:19.4750597Z 600: [2023-07-06T18:01:19.4745608Z] ERROR : File: D:\a\_work\1\s\build\_deps\vcpkg-src\buildtrees\azure-uamqp-c\src\c044281abc-36c14e2ea1.clean\src\connection.c:722 Func: connection_on_bytes_received: Cannot process received bytes
2023-07-06T18:01:19.4751722Z 600: 
2023-07-06T18:01:19.4752508Z 600: [  INFO ] D:\a\_work\1\s\sdk\core\azure-core-amqp\test\ut\message_sender_receiver.cpp(537):: Send Complete!
2023-07-06T18:01:19.4755747Z 600: unknown file: error: SEH exception with code 0xc0000005 thrown in the test body.
2023-07-06T18:01:19.4757024Z 600: [  FAILED  ] TestMessages.SenderSendAsync (30877 ms)
2023-07-06T18:01:19.4758370Z 600: [----------] 1 test from TestMessages (30877 ms total)
2023-07-06T18:01:19.4758945Z 600: 
2023-07-06T18:01:19.4759525Z 600: [----------] Global test environment tear-down
2023-07-06T18:01:19.4761016Z 600: [==========] 1 test from 1 test suite ran. (30878 ms total)
2023-07-06T18:01:19.4761547Z 600: [  PASSED  ] 0 tests.
2023-07-06T18:01:19.4762342Z 600: [  FAILED  ] 1 test, listed below:
2023-07-06T18:01:19.4762785Z 600: [  FAILED  ] TestMessages.SenderSendAsync
```

**Comment by LarryOsterman** [comment] 2023-08-04 23:17
Duplicate of #4707

**Closed by LarryOsterman** 2023-08-04 23:17 UTC
Labels: Azure.Core, test-reliability
