### ISSUE TITLE
Possible concurrency issues in storage common

### ISSUE THREAD

**Issue by gearama** [Azure/azure-sdk-for-cpp#4435] opened 2023-03-10 22:31 UTC
valgrind --tool=drd ./azure-storage-common-test &> ~/stor-common_thread.txt

[stor-common_thread.log](https://github.com/Azure/azure-sdk-for-cpp/files/10946682/stor-common_thread.log)

==28543== For lists of detected and suppressed errors, rerun with: -s
==28543== ERROR SUMMARY: 13 errors from 10 contexts (suppressed: 10 from 6)

**Comment by Jinming-Hu** [comment] 2023-03-14 05:19
I looked through the log. Almost all of the errors happened in libcurl transport layer, moving connections from/to the pool, cleaning up stuff.
These errors were found in storage tests only because storage internally calls into libcurl.
How about your team take a look first, and let us team know if you find anything that's specific to storage. @gearama

**Comment by Jinming-Hu** [comment] 2023-08-14 06:17
Ok, this issue was assigned back to storage without additional information.

All of these issues are in core SDK. For example the first one:

```
==28543== The impossible happened: mutex is locked simultaneously by two threads: mutex 0xb9df18, recursion count 1, owner 3.
==28543==    at 0x485AD1C: pthread_mutex_lock@* (in /usr/libexec/valgrind/vgpreload_drd-amd64-linux.so)
==28543==    by 0x3BDA24: __gthread_mutex_lock(pthread_mutex_t*) (gthr-default.h:749)
==28543==    by 0x3BDA79: std::mutex::lock() (std_mutex.h:100)
==28543==    by 0x7832F0: std::unique_lock<std::mutex>::lock() (unique_lock.h:139)
==28543==    by 0x7817D4: std::unique_lock<std::mutex>::unique_lock(std::mutex&) (unique_lock.h:69)
==28543==    by 0x77C281: Azure::Core::Http::_detail::CurlConnectionPool::MoveConnectionBackToPool(std::unique_ptr<Azure::Core::Http::CurlNetworkConnection, std::default_delete<Azure::Core::Http::CurlNetworkConnection> >, Azure::Core::Http::HttpStatusCode) (curl.cpp:2145)
==28543==    by 0x7807AD: Azure::Core::Http::CurlSession::~CurlSession() (curl_session_private.hpp:416)
==28543==    by 0x780853: Azure::Core::Http::CurlSession::~CurlSession() (curl_session_private.hpp:419)
==28543==    by 0x1AD23F: std::default_delete<Azure::Core::IO::BodyStream>::operator()(Azure::Core::IO::BodyStream*) const (unique_ptr.h:85)
==28543==    by 0x1AB5EF: std::unique_ptr<Azure::Core::IO::BodyStream, std::default_delete<Azure::Core::IO::BodyStream> >::~unique_ptr() (unique_ptr.h:361)
==28543==    by 0x79B9C6: Azure::Core::Http::Policies::_internal::TransportPolicy::Send(Azure::Core::Http::Request&, Azure::Core::Http::Policies::NextHttpPolicy, Azure::Core::Context const&) const (transport_policy.cpp:139)
==28543==    by 0x7958DB: Azure::Core::Http::Policies::NextHttpPolicy::Send(Azure::Core::Http::Request&, Azure::Core::Context const&) (policy.cpp:21)
==28543== mutex 0xb9df18 was first observed at:
==28543==    at 0x485AC58: pthread_mutex_lock@* (in /usr/libexec/valgrind/vgpreload_drd-amd64-linux.so)
==28543==    by 0x3BDA24: __gthread_mutex_lock(pthread_mutex_t*) (gthr-default.h:749)
==28543==    by 0x3BDA79: std::mutex::lock() (std_mutex.h:100)
==28543==    by 0x7832F0: std::unique_lock<std::mutex>::lock() (unique_lock.h:139)
==28543==    by 0x7817D4: std::unique_lock<std::mutex>::unique_lock(std::mutex&) (unique_lock.h:69)
==28543==    by 0x77BCF9: Azure::Core::Http::_detail::CurlConnectionPool::ExtractOrCreateCurlConnection(Azure::Core::Http::Request&, Azure::Core::Http::CurlTransportOptions const&, bool) (curl.cpp:2073)
==28543==    by 0x775756: Azure::Core::Http::CurlTransport::Send(Azure::Core::Http::Request&, Azure::Core::Context const&) (curl.cpp:347)
==28543==    by 0x79B908: Azure::Core::Http::Policies::_internal::TransportPolicy::Send(Azure::Core::Http::Request&, Azure::Core::Http::Policies::NextHttpPolicy, Azure::Core::Context const&) const (transport_policy.cpp:120)
==28543==    by 0x7958DB: Azure::Core::Http::Policies::NextHttpPolicy::Send(Azure::Core::Http::Request&, Azure::Core::Context const&) (policy.cpp:21)
==28543==    by 0x7945BC: Azure::Core::Http::Policies::_internal::LogPolicy::Send(Azure::Core::Http::Request&, Azure::Core::Http::Policies::NextHttpPolicy, Azure::Core::Context const&) const (log_policy.cpp:114)
==28543==    by 0x7958DB: Azure::Core::Http::Policies::NextHttpPolicy::Send(Azure::Core::Http::Request&, Azure::Core::Context const&) (policy.cpp:21)
==28543==    by 0x79715B: Azure::Core::Http::Policies::_internal::RequestActivityPolicy::Send(Azure::Core::Http::Request&, Azure::Core::Http::Policies::NextHttpPolicy, Azure::Core::Context const&) const (request_activity_policy.cpp:110)
```

I'm not sure why this happened but the two threads competing for the lock, one was trying to put a connection back to the pool, the other was trying to get a new connection from the pool.




Another one:

```
==28543== condition variable has not been initialized: cond 0xb9df40
==28543==    at 0x486159B: pthread_cond_signal@* (in /usr/libexec/valgrind/vgpreload_drd-amd64-linux.so)
==28543==    by 0x780102: Azure::Core::Http::_detail::CurlConnectionPool::~CurlConnectionPool() (curl_connection_pool_private.hpp:64)
==28543==    by 0x4BFC494: __run_exit_handlers (exit.c:113)
==28543==    by 0x4BFC60F: exit (exit.c:143)
==28543==    by 0x4BE0D96: (below main) (libc_start_call_main.h:74)
```

This implies a non-initialized condition variable was destructed in the destructor of `CulrConnectionPool`.

**Comment by Jinming-Hu** [comment] 2023-08-14 06:19
I'll close this issue and all relevant ones because they are non-storage issues.

If anybody finds any memory issues caused by storage code, feel free to open new issues and assign to storage.

**Closed by Jinming-Hu** 2023-08-14 06:19 UTC
Labels: bug, Client, Storage
