### ISSUE TITLE
[Storage File Service] test case failed

### ISSUE THREAD

**Issue by Jinming-Hu** [Azure/azure-sdk-for-cpp#405] opened 2020-08-06 02:32 UTC
[ RUN      ] FileShareServiceClientTest.SetProperties
unknown file: Failure
C++ exception with description "400 XML specified is not syntactically valid.
XML specified is not syntactically valid.
RequestId:d81ba568-a01a-0028-7f99-6b2d97000000
Time:2020-08-06T02:30:03.2801867Z
Request ID: d81ba568-a01a-0028-7f99-6b2d97000000" thrown in the test body.

**Comment by katmsft** [comment] 2020-08-19 08:10
Close due to unable to reproduce, please reopen if reproduces.

**Comment by Jinming-Hu** [comment] 2020-09-08 03:15
```
[ RUN      ] FileShareServiceClientTest.SetProperties
unknown file: Failure
C++ exception with description "400 XML specified is not syntactically valid.
XML specified is not syntactically valid.
RequestId:150944bc-e01a-002e-448e-85750a000000
Time:2020-09-08T03:14:07.1385688Z
Request ID: 150944bc-e01a-002e-448e-85750a000000" thrown in the test body.
```

occurred with the latest master commit a4b1677c38259bed3d79f62020d73b18479497b3

**Comment by Jinming-Hu** [comment] 2020-09-08 03:51
try to reproduce by running this test case on a newly-created storage account

**Comment by katmsft** [comment] 2020-10-26 02:26
Fixed by https://github.com/Azure/azure-sdk-for-cpp/pull/844.

**Closed** 2020-11-12 14:26 UTC
Labels: Client, Storage, blocking-release, test bug
