### ISSUE TITLE
nlohmann/json included publically in Storage headers

### ISSUE THREAD

**Issue by antkmsft** [Azure/azure-sdk-for-cpp#1173] opened 2020-12-14 19:23 UTC
We should not be exposing them, it is a part of implementation.

**Comment by ahsonkhan** [comment] 2020-12-14 20:53
This looks like a duplicate of https://github.com/Azure/azure-sdk-for-cpp/issues/1009, close?

**Comment by ahsonkhan** [comment] 2020-12-14 20:53
Accidentally closed, leaving it up to you to decide.

**Closed** 2020-12-14 21:49 UTC
Labels: Storage
