### ISSUE TITLE
Template pipeline failing on SetPipelineVersion.ps1

### ISSUE THREAD

**Issue by danieljurek** [Azure/azure-sdk-for-cpp#3503] opened 2022-04-04 17:12 UTC
See failure: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1474753&view=logs&j=ea7a2a59-09c4-504e-5213-fbfab7ea6e2d&t=99ad4bf0-a5b8-5e6a-b021-f23080a5f4b7

Likely because it's possible that there are no template release tags. 

Possible problem code -- https://github.com/Azure/azure-sdk-for-cpp/blob/main/eng/common/scripts/SetTestPipelineVersion.ps1#L23

**Comment by kurtzeborn** [comment] 2022-06-27 20:32
@chidozieononiwu, we're pretty sure you'll now what's going on here based on your previous work in this area. Would you mind taking a quick look at this?

**Comment by chidozieononiwu** [comment] 2022-06-27 23:21
@danieljurek is right about the cause of the failure. I improve the code to check for nulls

**Comment by chidozieononiwu** [comment] 2022-07-08 19:05
This has been resolved by https://github.com/Azure/azure-sdk-tools/pull/3546

**Closed as completed by chidozieononiwu** 2022-07-08 19:05 UTC
Labels: Central-EngSys
