### ISSUE TITLE
Possible concurency issues in storage datalake

### ISSUE THREAD

**Issue by gearama** [Azure/azure-sdk-for-cpp#4438] opened 2023-03-10 22:50 UTC
valgrind --tool=drd ./azure-storage-files-datalake-test &> ~/datalake_thread.txt

[datalake_thread.log](https://github.com/Azure/azure-sdk-for-cpp/files/10946724/datalake_thread.log)

**Comment by Jinming-Hu** [comment] 2023-08-14 06:20
duplicate of https://github.com/Azure/azure-sdk-for-cpp/issues/4435

**Closed by Jinming-Hu** 2023-08-14 06:20 UTC
Labels: bug, Client, Storage
