### ISSUE TITLE
C++ SDK for Azure Service Bus

### ISSUE THREAD

**Issue by 0xar1** [Azure/azure-sdk-for-cpp#5983] opened 2024-09-13 08:56 UTC
**Query/Question**
Hello, is there an SDK available for C++ to query Azure Service Bus? I couldn't find anything on this except a feature request. If there's a branch where development has started, I'd be happy to contribute. Can someone point me in the right direction?

***Why is this not a Bug or a feature Request?***
Couldn't find anything related to this other than feature request... 

**Setup (please complete the following information if applicable):**
 - OS: Ubuntu 22
 - IDE : IntelliJ
 - Latest
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ + ] Query Added
- [ + ] Setup information Added

**Comment by ahsonkhan** [comment] 2024-09-14 19:32
Hi @0xar1, thanks for the feature request. We don't currently have Azure Service Bus support in C++.
Can you please help us understand your application and usage scenarios that requires an SDK for it? What are you trying to build and do? We are looking for customer requests like yours to help motivate and drive the effort, so providing some context would be quite helpful.

cc @ronniegeraghty, @RickWinter

**Comment by RickWinter** [comment] 2024-09-16 21:21
Closing as a duplicate of #3981

**Closed by RickWinter** 2024-09-16 21:21 UTC
Labels: feature-request, customer-reported, needs-team-attention, Service Bus

**Comment by 0xar1** [comment] 2024-09-23 06:12
> Hi @0xar1, thanks for the feature request. We don't currently have Azure Service Bus support in C++. Can you please help us understand your application and usage scenarios that requires an SDK for it? What are you trying to build and do? We are looking for customer requests like yours to help motivate and drive the effort, so providing some context would be quite helpful.
> 
> cc @ronniegeraghty, @RickWinter

Use mysql to query from service bus.
