### ISSUE TITLE
Can't build on Windows from command prompt with Ninja

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk-for-cpp#1228] opened 2020-12-19 00:31 UTC
Getting unresolved symbols when linking storage test exe

```
azure-storage-common.lib(crypt.cpp.obj) : error LNK2019: unresolved external symbol __imp__CryptStringToBinaryA@28 referenced in function "class std::vector<unsigned char,class std::allocator<unsigned char> > __cdecl Azure::Storage::Base64Decode(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?Base64Decode@Storage@Azure@@YA?AV?$vector@EV?$allocator@E@std@@@std@@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@4@@Z)
azure-storage-common.lib(crypt.cpp.obj) : error LNK2019: unresolved external symbol __imp__CryptBinaryToStringA@20 referenced in function "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl Azure::Storage::Base64Encode(class std::vector<unsigned char,class std::allocator<unsigned char> > const &)" (?Base64Encode@Storage@Azure@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@ABV?$vector@EV?$allocator@E@std@@@4@@Z)
sdk\storage\azure-storage-test.exe : fatal error LNK1120: 2 unresolved externals
[102/102] Linking CXX executable sdk\template\azure-template\test\azure-template-test.exe
ninja: build stopped: subcommand failed.
```

Building windows x86

From Windows Developer command run
```
cmake -GNinja -DBUILD_TESTING=ON ..
cmake --build .
```

**Comment by Jinming-Hu** [comment] 2020-12-19 03:36
I can reproduce this issue and I believe it will be fixed in #1230.

But I'm still curious, the dependency has been existing for like several months and why this issue wasn't found until yesterday.

**Closed** 2020-12-19 04:45 UTC
Labels: Client, Storage, bug

**Comment by ahsonkhan** [comment] 2020-12-21 19:26
> But I'm still curious, the dependency has been existing for like several months and why this issue wasn't found until yesterday.

If I had to guess, it likely is because we don't test and build on Ninja often (or in CI), and it was discovered by doing adhoc testing on different build systems.

**Comment by vhvb1989** [comment] 2021-01-04 17:30
yeah, @ahsonkhan  is correct. We don't use Ninja for CI. (we use Visual Studio 2019 project for all Windows gates)
I am expecting to work with @danieljurek to enable at least on of the gates with Ninja.

This was discovered by trying to do it manually/locally in my PC
