### ISSUE TITLE
Merge curl and winhttp transport adapter tests in one only parametrized test 

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk-for-cpp#1216] opened 2020-12-18 07:28 UTC
Instead of having two param-supported tests, let's have just one and use the parameters correctly to provide the transport adapter

**Comment by ahsonkhan** [comment] 2020-12-18 18:58
Duplicate of https://github.com/Azure/azure-sdk-for-cpp/issues/1087

**Closed** 2020-12-18 22:21 UTC
Labels: Azure.Core, Client
