### ISSUE TITLE
Possible concurency issue in storage shares

### ISSUE THREAD

**Issue by gearama** [Azure/azure-sdk-for-cpp#4437] opened 2023-03-10 22:46 UTC
valgrind --tool=drd ./azure-storage-files-shares-test &> ~/shares_thread.txt

[shares_thread.log](https://github.com/Azure/azure-sdk-for-cpp/files/10946717/shares_thread.log)

Log incomplete , run died due to taking too long

**Comment by Jinming-Hu** [comment] 2023-08-14 06:20
duplicate of https://github.com/Azure/azure-sdk-for-cpp/issues/4435

**Closed by Jinming-Hu** 2023-08-14 06:20 UTC
Labels: bug, Client, Storage
