### ISSUE TITLE
[Identity] Add Readme for Identity like the other langs

### ISSUE THREAD

**Issue by vhvb1989** [Azure/azure-sdk-for-cpp#2020] opened 2021-04-01 17:01 UTC
Please add Readme for Identity with description for what's supported and available on C++, just like the one from .Net: https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/identity/Azure.Identity/README.md

The current Readme is too general: https://github.com/Azure/azure-sdk-for-cpp/tree/master/sdk/identity/azure-identity

**Comment by antkmsft** [comment] 2021-04-01 17:03
Duplicate of #1950?

**Closed** 2021-04-01 19:01 UTC
Labels: Azure.Identity, Client, Docs
