### ISSUE TITLE
remove copyright statements from vcpkg PR

### ISSUE THREAD

**Issue by Jinming-Hu** [Azure/azure-sdk-for-cpp#1676] opened 2021-02-12 05:36 UTC
remove

```
# Copyright (c) Microsoft Corporation. All rights reserved.
# SPDX-License-Identifier: MIT
#
```

from files in vcpkg PR. Because vcpkg guys don't like it

**Comment by RickWinter** [comment] 2021-02-12 19:27
@danieljurek We should automate removing this.

**Comment by RickWinter** [comment] 2021-02-12 19:29
Duplicate of #1664

**Closed by RickWinter** 2021-02-12 19:29 UTC
Labels: Client, EngSys, bug, duplicate
